DROP DATABASE IF EXISTS hospital_db;
CREATE DATABASE hospital_db;
USE hospital_db;

CREATE TABLE IF NOT EXISTS payers (
    Id CHAR(36) PRIMARY KEY,
    NAME VARCHAR(100),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    STATE_HEADQUARTERED CHAR(2),
    ZIP VARCHAR(10),
    PHONE VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS patients (
    Id CHAR(36) PRIMARY KEY,
    BIRTHDATE DATE,
    DEATHDATE DATE,
    PREFIX VARCHAR(10),
    FIRST VARCHAR(100),
    LAST VARCHAR(100),
    SUFFIX VARCHAR(10),
    MAIDEN VARCHAR(100),
    MARITAL CHAR(1),
    RACE VARCHAR(50),
    ETHNICITY VARCHAR(50),
    GENDER CHAR(1),
    BIRTHPLACE VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTY VARCHAR(100),
    ZIP VARCHAR(10),
    LAT DOUBLE,
    LON DOUBLE
);


CREATE TABLE encounters (
    Id INT PRIMARY KEY,
    START DATETIME,
    STOP DATETIME,
    PATIENT INT,
    ORGANIZATION VARCHAR(100),
    PAYER INT,
    ENCOUNTERCLASS VARCHAR(50),
    CODE VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    BASE_ENCOUNTER_COST DECIMAL(10,2),
    TOTAL_CLAIM_COST DECIMAL(10,2),
    PAYER_COVERAGE DECIMAL(10,2),
    REASONCODE VARCHAR(50),
    REASONDESCRIPTION VARCHAR(255)
);

CREATE TABLE procedures (
    Id INT PRIMARY KEY,
    START DATETIME,
    STOP DATETIME,
    PATIENT INT,
    ENCOUNTER INT,
    CODE VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    BASE_COST DECIMAL(10,2),
    REASONCODE VARCHAR(50),
    REASONDESCIPTION VARCHAR(255)
);

